package com.globalisosecurity.backend.dto;

import java.util.List;

public class ReporteResumenDTO {
    private Long empresaId; private String empresaNombre; private Long servicioId; private String sector; private String estadoServicio;
    private int totalServicios; private int totalEvaluaciones; private int totalFirmas; private int totalCapacitaciones; private List<String> estadosServicios;
    private int totalControles; private int controlesAplicables; private int controlesNoAplicables; private int controlesPendientes; private int controlesImplementados; private int porcentajeImplementacion;
    private int totalRiesgos; private int riesgosCriticos; private int riesgosAltos; private int evidenciasValidadas; private int evidenciasPendientes; private int evidenciasRechazadas; private int alertasRpm;
    private List<SoaFila> soa; private List<RiesgoFila> riesgos; private List<RpmFila> rpm;
    public record SoaFila(String codigo,String titulo,String dominio,String aplicabilidad,String justificacion,String estado,Integer porcentaje,String responsable,String fechaObjetivo,long evidencias,long riesgos){}
    public record RiesgoFila(String codigo,String nombre,String activo,Integer probabilidad,Integer impacto,Integer nivel,String categoria,String tratamiento,String estado,String controles){}
    public record RpmFila(String control,String prioridad,Integer puntaje,String prioridadMl,Double confianzaMl,String versionModeloMl,String estado,String resumen,String acciones){}
    public Long getEmpresaId(){return empresaId;} public void setEmpresaId(Long v){empresaId=v;} public String getEmpresaNombre(){return empresaNombre;} public void setEmpresaNombre(String v){empresaNombre=v;} public Long getServicioId(){return servicioId;} public void setServicioId(Long v){servicioId=v;} public String getSector(){return sector;} public void setSector(String v){sector=v;} public String getEstadoServicio(){return estadoServicio;} public void setEstadoServicio(String v){estadoServicio=v;}
    public int getTotalServicios(){return totalServicios;} public void setTotalServicios(int v){totalServicios=v;} public int getTotalEvaluaciones(){return totalEvaluaciones;} public void setTotalEvaluaciones(int v){totalEvaluaciones=v;} public int getTotalFirmas(){return totalFirmas;} public void setTotalFirmas(int v){totalFirmas=v;} public int getTotalCapacitaciones(){return totalCapacitaciones;} public void setTotalCapacitaciones(int v){totalCapacitaciones=v;} public List<String> getEstadosServicios(){return estadosServicios;} public void setEstadosServicios(List<String> v){estadosServicios=v;}
    public int getTotalControles(){return totalControles;} public void setTotalControles(int v){totalControles=v;} public int getControlesAplicables(){return controlesAplicables;} public void setControlesAplicables(int v){controlesAplicables=v;} public int getControlesNoAplicables(){return controlesNoAplicables;} public void setControlesNoAplicables(int v){controlesNoAplicables=v;} public int getControlesPendientes(){return controlesPendientes;} public void setControlesPendientes(int v){controlesPendientes=v;} public int getControlesImplementados(){return controlesImplementados;} public void setControlesImplementados(int v){controlesImplementados=v;} public int getPorcentajeImplementacion(){return porcentajeImplementacion;} public void setPorcentajeImplementacion(int v){porcentajeImplementacion=v;}
    public int getTotalRiesgos(){return totalRiesgos;} public void setTotalRiesgos(int v){totalRiesgos=v;} public int getRiesgosCriticos(){return riesgosCriticos;} public void setRiesgosCriticos(int v){riesgosCriticos=v;} public int getRiesgosAltos(){return riesgosAltos;} public void setRiesgosAltos(int v){riesgosAltos=v;} public int getEvidenciasValidadas(){return evidenciasValidadas;} public void setEvidenciasValidadas(int v){evidenciasValidadas=v;} public int getEvidenciasPendientes(){return evidenciasPendientes;} public void setEvidenciasPendientes(int v){evidenciasPendientes=v;} public int getEvidenciasRechazadas(){return evidenciasRechazadas;} public void setEvidenciasRechazadas(int v){evidenciasRechazadas=v;} public int getAlertasRpm(){return alertasRpm;} public void setAlertasRpm(int v){alertasRpm=v;}
    public List<SoaFila> getSoa(){return soa;} public void setSoa(List<SoaFila> v){soa=v;} public List<RiesgoFila> getRiesgos(){return riesgos;} public void setRiesgos(List<RiesgoFila> v){riesgos=v;} public List<RpmFila> getRpm(){return rpm;} public void setRpm(List<RpmFila> v){rpm=v;}
}
