server {
    listen ${PORT};
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 50m;

    location = / {
        return 302 /pages/login.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    # Render Free no usa red privada entre servicios.
    # Por eso el frontend hace proxy hacia la URL publica del backend.
    # El frontend puede seguir usando /api en los archivos JS.
    location /api/ {
        proxy_pass ${BACKEND_URL}/api/;
        proxy_http_version 1.1;

        proxy_ssl_server_name on;
        proxy_ssl_name globaliso-backend-cito515432.onrender.com;

        proxy_set_header Host globaliso-backend-cito515432.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_connect_timeout 180s;
        proxy_send_timeout 180s;
        proxy_read_timeout 180s;
    }
}
