-- Actualización de controles ISO 27001 por sector para Global ISO Security
-- Ejecutar una sola vez en TiDB/MySQL sobre la base globalisosecurity.
USE globalisosecurity;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM evaluaciones WHERE item_checklist_id IN (SELECT id FROM items_checklist WHERE checklist_id IN (1,2,3,4));
DELETE FROM items_checklist WHERE checklist_id IN (1,2,3,4);
SET FOREIGN_KEY_CHECKS = 1;

UPDATE checklists SET descripcion = 'Checklist ISO 27001 dinámico para sector Salud' WHERE id = 1;
UPDATE checklists SET descripcion = 'Checklist ISO 27001 dinámico para sector Educación' WHERE id = 2;
UPDATE checklists SET descripcion = 'Checklist ISO 27001 dinámico para sector Financiero' WHERE id = 3;
UPDATE checklists SET descripcion = 'Checklist ISO 27001 dinámico para sector Tecnología' WHERE id = 4;

INSERT INTO items_checklist (estado, observacion, pregunta, respuesta, checklist_id) VALUES
('PENDIENTE', NULL, 'A.5.1 — Políticas de seguridad de la información: ¿Existe una política de seguridad aprobada, comunicada y revisada?', NULL, 1),
('PENDIENTE', NULL, 'A.5.2 — Roles y responsabilidades: ¿Están definidos los responsables de seguridad de la información?', NULL, 1),
('PENDIENTE', NULL, 'A.5.7 — Inteligencia de amenazas: ¿La organización identifica amenazas relevantes para su operación?', NULL, 1),
('PENDIENTE', NULL, 'A.5.15 — Control de acceso: ¿Existe una política formal de control de acceso basada en roles?', NULL, 1),
('PENDIENTE', NULL, 'A.5.23 — Seguridad en servicios en la nube: ¿Se evalúan proveedores cloud y sus responsabilidades de seguridad?', NULL, 1),
('PENDIENTE', NULL, 'A.6.3 — Concienciación y formación: ¿El personal recibe capacitación periódica en seguridad de la información?', NULL, 1),
('PENDIENTE', NULL, 'A.6.7 — Trabajo remoto: ¿Se protegen dispositivos y accesos usados fuera de las instalaciones?', NULL, 1),
('PENDIENTE', NULL, 'A.7.1 — Perímetros físicos: ¿Existen controles físicos para proteger áreas críticas?', NULL, 1),
('PENDIENTE', NULL, 'A.8.2 — Derechos de acceso privilegiado: ¿Los accesos administrativos están controlados y revisados?', NULL, 1),
('PENDIENTE', NULL, 'A.8.5 — Autenticación segura: ¿Se usa autenticación fuerte para sistemas críticos?', NULL, 1),
('PENDIENTE', NULL, 'A.8.9 — Gestión de configuración: ¿Los sistemas tienen configuraciones seguras documentadas?', NULL, 1),
('PENDIENTE', NULL, 'A.8.13 — Copias de seguridad: ¿Se realizan backups y pruebas de restauración?', NULL, 1),
('PENDIENTE', NULL, 'A.8.15 — Registro de eventos: ¿Se conservan logs de seguridad y actividad relevante?', NULL, 1),
('PENDIENTE', NULL, 'A.8.16 — Monitoreo: ¿Se monitorean eventos de seguridad para detectar incidentes?', NULL, 1),
('PENDIENTE', NULL, 'A.8.24 — Uso de criptografía: ¿La información sensible se protege con cifrado adecuado?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-01 — Historia clínica: ¿La información clínica tiene acceso restringido por rol asistencial o administrativo?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-02 — Datos sensibles de pacientes: ¿Se protegen diagnósticos, resultados y datos personales de pacientes?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-03 — Consentimiento y privacidad: ¿Se informa al paciente sobre el tratamiento de sus datos?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-04 — Sistemas clínicos: ¿Se controla el acceso a software médico, agenda y admisiones?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-05 — Trazabilidad clínica: ¿Se registra quién consulta, modifica o elimina información del paciente?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-06 — Interoperabilidad: ¿Se valida la seguridad al intercambiar información con laboratorios, EPS o terceros?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-07 — Disponibilidad asistencial: ¿Existen planes para mantener sistemas críticos durante contingencias?', NULL, 1),
('PENDIENTE', NULL, 'SALUD-08 — Dispositivos médicos: ¿Los equipos conectados están inventariados y protegidos?', NULL, 1),
('PENDIENTE', NULL, 'A.5.1 — Políticas de seguridad de la información: ¿Existe una política de seguridad aprobada, comunicada y revisada?', NULL, 2),
('PENDIENTE', NULL, 'A.5.2 — Roles y responsabilidades: ¿Están definidos los responsables de seguridad de la información?', NULL, 2),
('PENDIENTE', NULL, 'A.5.7 — Inteligencia de amenazas: ¿La organización identifica amenazas relevantes para su operación?', NULL, 2),
('PENDIENTE', NULL, 'A.5.15 — Control de acceso: ¿Existe una política formal de control de acceso basada en roles?', NULL, 2),
('PENDIENTE', NULL, 'A.5.23 — Seguridad en servicios en la nube: ¿Se evalúan proveedores cloud y sus responsabilidades de seguridad?', NULL, 2),
('PENDIENTE', NULL, 'A.6.3 — Concienciación y formación: ¿El personal recibe capacitación periódica en seguridad de la información?', NULL, 2),
('PENDIENTE', NULL, 'A.6.7 — Trabajo remoto: ¿Se protegen dispositivos y accesos usados fuera de las instalaciones?', NULL, 2),
('PENDIENTE', NULL, 'A.7.1 — Perímetros físicos: ¿Existen controles físicos para proteger áreas críticas?', NULL, 2),
('PENDIENTE', NULL, 'A.8.2 — Derechos de acceso privilegiado: ¿Los accesos administrativos están controlados y revisados?', NULL, 2),
('PENDIENTE', NULL, 'A.8.5 — Autenticación segura: ¿Se usa autenticación fuerte para sistemas críticos?', NULL, 2),
('PENDIENTE', NULL, 'A.8.9 — Gestión de configuración: ¿Los sistemas tienen configuraciones seguras documentadas?', NULL, 2),
('PENDIENTE', NULL, 'A.8.13 — Copias de seguridad: ¿Se realizan backups y pruebas de restauración?', NULL, 2),
('PENDIENTE', NULL, 'A.8.15 — Registro de eventos: ¿Se conservan logs de seguridad y actividad relevante?', NULL, 2),
('PENDIENTE', NULL, 'A.8.16 — Monitoreo: ¿Se monitorean eventos de seguridad para detectar incidentes?', NULL, 2),
('PENDIENTE', NULL, 'A.8.24 — Uso de criptografía: ¿La información sensible se protege con cifrado adecuado?', NULL, 2),
('PENDIENTE', NULL, 'EDU-01 — Datos de estudiantes: ¿Se protegen calificaciones, matrículas, acudientes y expedientes académicos?', NULL, 2),
('PENDIENTE', NULL, 'EDU-02 — Plataformas virtuales: ¿Se controlan accesos a LMS, aulas virtuales y repositorios académicos?', NULL, 2),
('PENDIENTE', NULL, 'EDU-03 — Menores de edad: ¿Se aplican controles adicionales para datos de menores?', NULL, 2),
('PENDIENTE', NULL, 'EDU-04 — Evaluaciones: ¿Se protege la integridad de exámenes, rúbricas y resultados?', NULL, 2),
('PENDIENTE', NULL, 'EDU-05 — Investigación: ¿Se clasifican datos de proyectos, semilleros o investigaciones sensibles?', NULL, 2),
('PENDIENTE', NULL, 'EDU-06 — Correo institucional: ¿Se aplican controles contra phishing y suplantación?', NULL, 2),
('PENDIENTE', NULL, 'EDU-07 — Laboratorios y equipos compartidos: ¿Existen políticas para sesiones, usuarios y limpieza de datos?', NULL, 2),
('PENDIENTE', NULL, 'EDU-08 — Publicación de información: ¿Se revisa que portales y documentos no expongan datos personales?', NULL, 2),
('PENDIENTE', NULL, 'A.5.1 — Políticas de seguridad de la información: ¿Existe una política de seguridad aprobada, comunicada y revisada?', NULL, 3),
('PENDIENTE', NULL, 'A.5.2 — Roles y responsabilidades: ¿Están definidos los responsables de seguridad de la información?', NULL, 3),
('PENDIENTE', NULL, 'A.5.7 — Inteligencia de amenazas: ¿La organización identifica amenazas relevantes para su operación?', NULL, 3),
('PENDIENTE', NULL, 'A.5.15 — Control de acceso: ¿Existe una política formal de control de acceso basada en roles?', NULL, 3),
('PENDIENTE', NULL, 'A.5.23 — Seguridad en servicios en la nube: ¿Se evalúan proveedores cloud y sus responsabilidades de seguridad?', NULL, 3),
('PENDIENTE', NULL, 'A.6.3 — Concienciación y formación: ¿El personal recibe capacitación periódica en seguridad de la información?', NULL, 3),
('PENDIENTE', NULL, 'A.6.7 — Trabajo remoto: ¿Se protegen dispositivos y accesos usados fuera de las instalaciones?', NULL, 3),
('PENDIENTE', NULL, 'A.7.1 — Perímetros físicos: ¿Existen controles físicos para proteger áreas críticas?', NULL, 3),
('PENDIENTE', NULL, 'A.8.2 — Derechos de acceso privilegiado: ¿Los accesos administrativos están controlados y revisados?', NULL, 3),
('PENDIENTE', NULL, 'A.8.5 — Autenticación segura: ¿Se usa autenticación fuerte para sistemas críticos?', NULL, 3),
('PENDIENTE', NULL, 'A.8.9 — Gestión de configuración: ¿Los sistemas tienen configuraciones seguras documentadas?', NULL, 3),
('PENDIENTE', NULL, 'A.8.13 — Copias de seguridad: ¿Se realizan backups y pruebas de restauración?', NULL, 3),
('PENDIENTE', NULL, 'A.8.15 — Registro de eventos: ¿Se conservan logs de seguridad y actividad relevante?', NULL, 3),
('PENDIENTE', NULL, 'A.8.16 — Monitoreo: ¿Se monitorean eventos de seguridad para detectar incidentes?', NULL, 3),
('PENDIENTE', NULL, 'A.8.24 — Uso de criptografía: ¿La información sensible se protege con cifrado adecuado?', NULL, 3),
('PENDIENTE', NULL, 'FIN-01 — Datos financieros: ¿Se clasifican y protegen cuentas, transacciones y soportes financieros?', NULL, 3),
('PENDIENTE', NULL, 'FIN-02 — Prevención de fraude: ¿Existen controles para detectar operaciones inusuales o no autorizadas?', NULL, 3),
('PENDIENTE', NULL, 'FIN-03 — Segregación de funciones: ¿Quien aprueba pagos es distinto de quien los registra o ejecuta?', NULL, 3),
('PENDIENTE', NULL, 'FIN-04 — Conciliaciones: ¿Se revisan transacciones críticas y conciliaciones con trazabilidad?', NULL, 3),
('PENDIENTE', NULL, 'FIN-05 — Accesos a banca y ERP: ¿Los sistemas financieros usan MFA y privilegios mínimos?', NULL, 3),
('PENDIENTE', NULL, 'FIN-06 — Retención de registros: ¿Se conservan soportes y logs de operaciones por el tiempo requerido?', NULL, 3),
('PENDIENTE', NULL, 'FIN-07 — Terceros financieros: ¿Se evalúa la seguridad de pasarelas de pago, bancos y proveedores?', NULL, 3),
('PENDIENTE', NULL, 'FIN-08 — Continuidad financiera: ¿Existe plan para operar pagos y reportes críticos ante fallas?', NULL, 3),
('PENDIENTE', NULL, 'A.5.1 — Políticas de seguridad de la información: ¿Existe una política de seguridad aprobada, comunicada y revisada?', NULL, 4),
('PENDIENTE', NULL, 'A.5.2 — Roles y responsabilidades: ¿Están definidos los responsables de seguridad de la información?', NULL, 4),
('PENDIENTE', NULL, 'A.5.7 — Inteligencia de amenazas: ¿La organización identifica amenazas relevantes para su operación?', NULL, 4),
('PENDIENTE', NULL, 'A.5.15 — Control de acceso: ¿Existe una política formal de control de acceso basada en roles?', NULL, 4),
('PENDIENTE', NULL, 'A.5.23 — Seguridad en servicios en la nube: ¿Se evalúan proveedores cloud y sus responsabilidades de seguridad?', NULL, 4),
('PENDIENTE', NULL, 'A.6.3 — Concienciación y formación: ¿El personal recibe capacitación periódica en seguridad de la información?', NULL, 4),
('PENDIENTE', NULL, 'A.6.7 — Trabajo remoto: ¿Se protegen dispositivos y accesos usados fuera de las instalaciones?', NULL, 4),
('PENDIENTE', NULL, 'A.7.1 — Perímetros físicos: ¿Existen controles físicos para proteger áreas críticas?', NULL, 4),
('PENDIENTE', NULL, 'A.8.2 — Derechos de acceso privilegiado: ¿Los accesos administrativos están controlados y revisados?', NULL, 4),
('PENDIENTE', NULL, 'A.8.5 — Autenticación segura: ¿Se usa autenticación fuerte para sistemas críticos?', NULL, 4),
('PENDIENTE', NULL, 'A.8.9 — Gestión de configuración: ¿Los sistemas tienen configuraciones seguras documentadas?', NULL, 4),
('PENDIENTE', NULL, 'A.8.13 — Copias de seguridad: ¿Se realizan backups y pruebas de restauración?', NULL, 4),
('PENDIENTE', NULL, 'A.8.15 — Registro de eventos: ¿Se conservan logs de seguridad y actividad relevante?', NULL, 4),
('PENDIENTE', NULL, 'A.8.16 — Monitoreo: ¿Se monitorean eventos de seguridad para detectar incidentes?', NULL, 4),
('PENDIENTE', NULL, 'A.8.24 — Uso de criptografía: ¿La información sensible se protege con cifrado adecuado?', NULL, 4),
('PENDIENTE', NULL, 'TEC-01 — Desarrollo seguro: ¿Se aplican prácticas de codificación segura y revisión de código?', NULL, 4),
('PENDIENTE', NULL, 'TEC-02 — Gestión de vulnerabilidades: ¿Se identifican, priorizan y corrigen vulnerabilidades técnicas?', NULL, 4),
('PENDIENTE', NULL, 'TEC-03 — Ambientes separados: ¿Producción, pruebas y desarrollo están separados?', NULL, 4),
('PENDIENTE', NULL, 'TEC-04 — Secretos y credenciales: ¿Las claves API, tokens y secretos se gestionan fuera del código fuente?', NULL, 4),
('PENDIENTE', NULL, 'TEC-05 — CI/CD: ¿Los pipelines de despliegue tienen controles de aprobación y trazabilidad?', NULL, 4),
('PENDIENTE', NULL, 'TEC-06 — Infraestructura cloud: ¿Se revisan configuraciones de red, permisos y almacenamiento cloud?', NULL, 4),
('PENDIENTE', NULL, 'TEC-07 — Logs de aplicación: ¿Se registran eventos de autenticación, errores y cambios críticos?', NULL, 4),
('PENDIENTE', NULL, 'TEC-08 — Respuesta a incidentes técnicos: ¿Existe procedimiento para caídas, fugas de datos y vulnerabilidades críticas?', NULL, 4);
