spring.application.name=backend
# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3308/globalisosecurity
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=GlobalIsoSecurity2026ClaveSecreta
jwt.expiration=86400000

# Puerto del servidor
server.port=8081