let auditorUser, auditorCompanyId, auditorServiceId, auditorService, auditorPortal, auditorSoa=[], auditorRisks=[], auditorEvidences=[], auditorFindings=[], auditorRpm=[], auditorSignatures=[], auditorReport;

document.addEventListener("DOMContentLoaded",async()=>{
  if(!App.requireAuth(["AUDITOR"]))return;
  App.bindNavigation();bindAuditorTitles();bindAuditorForms();
  try{auditorUser=await App.user();auditorCompanyId=auditorUser.empresa?.id;auditorService=await App.api("/servicios/mi-servicio");auditorServiceId=auditorService.servicioId;auditorCompanyId=auditorService.empresaId||auditorCompanyId;document.getElementById("serviceLabel").textContent=`Servicio #${auditorServiceId} · ${auditorService.sectorNombre||'Sin sector'} · ${App.pretty(auditorService.estado)}`;await refreshAuditor();}catch(e){showAuditorFatal(e.message);}
});
function bindAuditorTitles(){document.querySelectorAll("[data-section]").forEach(b=>b.addEventListener("click",()=>document.getElementById("pageTitle").textContent=b.textContent.trim()));}
function bindAuditorForms(){
  document.getElementById("evidenceValidationForm").addEventListener("submit",saveEvidenceValidation);
  document.getElementById("findingForm").addEventListener("submit",saveFinding);
  document.getElementById("signatureForm").addEventListener("submit",saveSignature);
  ["auditSoaSearch","auditSoaState","auditSoaIssue"].forEach(id=>document.getElementById(id).addEventListener("input",renderAuditSoa));
  ["auditEvidenceSearch","auditEvidenceState"].forEach(id=>document.getElementById(id).addEventListener("input",renderAuditEvidences));
  ["findingSearch","findingStatus","findingSeverity"].forEach(id=>document.getElementById(id).addEventListener("input",renderFindings));
  ["auditRpmSearch","auditRpmPriority"].forEach(id=>document.getElementById(id).addEventListener("input",renderAuditRpm));
}
async function refreshAuditor(){
  try{[auditorPortal,auditorSoa,auditorRisks,auditorEvidences,auditorFindings,auditorRpm,auditorSignatures,auditorReport]=await Promise.all([
    App.api(`/portal-empresa/empresa/${auditorCompanyId}`),App.api(`/soa/servicio/${auditorServiceId}`),App.api(`/riesgos/servicio/${auditorServiceId}`),App.api(`/evidencias/servicio/${auditorServiceId}`),App.api(`/hallazgos/servicio/${auditorServiceId}`),App.api(`/rpm/servicio/${auditorServiceId}`),App.api(`/firmas/servicio/${auditorServiceId}`),App.api(`/reportes/empresa/${auditorCompanyId}`)
  ]);populateAuditSelects();renderAuditorDashboard();renderAuditSoa();renderAuditEvidences();renderFindings();renderAuditRpm();renderSignatures();renderAuditReport();}catch(e){App.toast(e.message,"error");}
}
function auditMetric(label,value,icon,hint=""){return `<div class="card-app metric"><i class="bi ${icon} icon"></i><div class="label">${App.esc(label)}</div><div class="value">${App.esc(value)}</div><div class="hint">${App.esc(hint)}</div></div>`;}
function renderAuditorDashboard(){
  document.getElementById("auditorMetrics").innerHTML=[auditMetric("Evidencias pendientes",auditorPortal.evidencias.pendientes,"bi-hourglass-split"),auditMetric("Evidencias rechazadas",auditorPortal.evidencias.rechazadas,"bi-x-octagon"),auditMetric("Hallazgos abiertos",auditorPortal.hallazgos.abiertos,"bi-search",`${auditorPortal.hallazgos.recurrentes} recurrentes`),auditMetric("Hallazgos críticos",auditorPortal.hallazgos.criticos,"bi-radioactive"),auditMetric("Decisiones RPM",auditorPortal.rpm.pendientesValidacion,"bi-person-check"),auditMetric("Avance auditoría",`${auditorPortal.etapas.auditoria}%`,"bi-patch-check")].join("");
  const pendingEvidence=auditorEvidences.filter(e=>e.estado==='PENDIENTE').slice(0,5);const pendingDecisions=latestAuditRpm().flatMap(a=>a.decisiones.map(d=>({...d,control:a.controlCodigo}))).filter(d=>d.estado==='PENDIENTE').slice(0,5);
  document.getElementById("auditQueue").innerHTML=[...pendingEvidence.map(e=>`<div class="priority-card"><h4>Evidencia · ${App.esc(e.soaControl?.control?.codigo||'')}</h4><p>${App.esc(e.nombreOriginal)}</p><button class="btn-app mt-2" onclick="openEvidenceValidation(${e.id})">Revisar</button></div>`),...pendingDecisions.map(d=>`<div class="priority-card"><h4>RPM · ${App.esc(d.control)}</h4><p>${App.esc(d.accion)}</p><button class="btn-app mt-2" onclick="goAuditSection('rpm')">Validar</button></div>`)].join('')||'<div class="empty"><i class="bi bi-check2-all"></i>La cola de revisión está al día.</div>';
  const rec=auditorFindings.filter(h=>h.estado!=='CERRADO'&&h.recurrente);const pri=auditorPortal.prioridades.slice(0,5);document.getElementById("auditPriorities").innerHTML=[...pri.map(p=>`<div class="priority-card ${String(p.prioridad).toLowerCase()}"><div class="d-flex justify-content-between"><h4>${App.esc(p.controlCodigo)} · ${App.esc(p.controlTitulo)}</h4>${App.badge(p.prioridad)}</div><p>${App.esc(p.resumen)}</p></div>`),...rec.map(h=>`<div class="priority-card high"><div class="d-flex justify-content-between"><h4>Hallazgo recurrente · ${App.esc(h.titulo)}</h4>${App.badge(h.severidad)}</div><p>${App.esc(h.descripcion)}</p></div>`)].join('')||'<div class="empty">No hay prioridades activas.</div>';
}
function populateAuditSelects(){document.getElementById("findingSoa").innerHTML='<option value="">Sin control específico</option>'+auditorSoa.map(x=>`<option value="${x.id}">${App.esc(x.control.codigo)} · ${App.esc(x.control.titulo)}</option>`).join('');document.getElementById("findingRisk").innerHTML='<option value="">Sin riesgo específico</option>'+auditorRisks.map(x=>`<option value="${x.id}">${App.esc(x.codigo)} · ${App.esc(x.nombre)}</option>`).join('');}
function latestAuditRpm(){const seen=new Set();return auditorRpm.filter(x=>{const k=x.soaControlId||x.id;if(seen.has(k))return false;seen.add(k);return true;});}
function rpmForSoa(id){return latestAuditRpm().find(x=>x.soaControlId===id);}
function renderAuditSoa(){const q=document.getElementById("auditSoaSearch").value.toLowerCase(),state=document.getElementById("auditSoaState").value,issue=document.getElementById("auditSoaIssue").value;const data=auditorSoa.filter(x=>[x.control.codigo,x.control.titulo,x.responsable].some(v=>String(v||'').toLowerCase().includes(q))).filter(x=>!state||x.estadoImplementacion===state).filter(x=>!issue||(issue==='NO_EVIDENCE'&&x.evidencias.total===0)||(issue==='FINDINGS'&&x.hallazgosAbiertos>0)||(issue==='RISK'&&x.riesgos.length>0));document.getElementById("auditSoaTable").innerHTML=data.map(x=>{const a=rpmForSoa(x.id);return `<tr><td><strong>${App.esc(x.control.codigo)} · ${App.esc(x.control.titulo)}</strong><br><small class="text-muted-app">${App.esc(x.control.dominio)}</small></td><td>${App.badge(x.aplicabilidad)}<br><small class="text-muted-app">${App.esc(x.justificacionAplicabilidad||'Sin justificación')}</small></td><td>${App.badge(x.estadoImplementacion)}${App.progress(x.porcentajeImplementacion)}</td><td>${x.evidencias.total}<br><small class="text-muted-app">${x.evidencias.validadas} validadas · ${x.evidencias.rechazadas} rechazadas</small></td><td>${x.riesgos.length?x.riesgos.map(r=>`${App.esc(r.codigo)} ${App.badge(r.nivel)}`).join('<br>'):'—'}</td><td>${x.hallazgosAbiertos}</td><td>${a?`${App.badge(a.prioridad)} ${a.puntaje}/100`:'Sin análisis'}</td><td><button class="btn-app" onclick="openFindingModal(null,${x.id})"><i class="bi bi-search"></i> Hallazgo</button></td></tr>`;}).join('')||'<tr><td colspan="8" class="empty">No hay controles con esos filtros.</td></tr>';}
function renderAuditEvidences(){const q=document.getElementById("auditEvidenceSearch").value.toLowerCase(),st=document.getElementById("auditEvidenceState").value,today=new Date().toISOString().slice(0,10);const data=auditorEvidences.filter(e=>[e.nombreOriginal,e.descripcion,e.cargadaPor,e.soaControl?.control?.codigo].some(v=>String(v||'').toLowerCase().includes(q))).filter(e=>!st||e.estado===st);document.getElementById("auditEvidenceMetrics").innerHTML=[auditMetric("Total",auditorEvidences.length,"bi-paperclip"),auditMetric("Pendientes",auditorEvidences.filter(e=>e.estado==='PENDIENTE').length,"bi-hourglass"),auditMetric("Validadas",auditorEvidences.filter(e=>e.estado==='VALIDADA').length,"bi-patch-check"),auditMetric("Vencidas",auditorEvidences.filter(e=>e.fechaVencimiento&&e.fechaVencimiento<today).length,"bi-calendar-x")].join('');document.getElementById("auditEvidenceTable").innerHTML=data.map(e=>`<tr><td><strong>${App.esc(e.nombreOriginal)}</strong><br><small class="text-muted-app">${App.esc(e.tipoMime||'')}</small></td><td>${App.esc(e.soaControl?.control?.codigo||'—')}<br><small class="text-muted-app">${App.esc(e.soaControl?.control?.titulo||'')}</small></td><td>${App.esc(e.descripcion||'—')}<br><small class="text-muted-app">Cargada por ${App.esc(e.cargadaPor)}</small></td><td>${App.fmtDate(e.fechaVencimiento)}${e.fechaVencimiento&&e.fechaVencimiento<today?'<br><span class="badge-app b-high">Vencida</span>':''}</td><td>${App.badge(e.estado)}<br><small class="text-muted-app">${App.esc(e.observacionValidacion||'')}</small></td><td><code class="small-app">${App.esc((e.hashSha256||'').slice(0,16))}…</code></td><td class="nowrap"><button class="btn-app" onclick="downloadAuditEvidence(${e.id},${JSON.stringify(e.nombreOriginal)})"><i class="bi bi-download"></i></button> <button class="btn-app btn-primary-app" onclick="openEvidenceValidation(${e.id})"><i class="bi bi-patch-check"></i></button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No hay evidencias.</td></tr>';}
function openEvidenceValidation(id){const e=auditorEvidences.find(x=>x.id===id);if(!e)return;document.getElementById("evidenceValidationId").value=id;document.getElementById("evidenceValidationState").value=e.estado==='RECHAZADA'?'RECHAZADA':'VALIDADA';document.getElementById("evidenceValidationNote").value=e.observacionValidacion||'';document.getElementById("evidenceValidationInfo").innerHTML=`<h4>${App.esc(e.nombreOriginal)}</h4><p>${App.esc(e.soaControl?.control?.codigo||'')} · ${App.esc(e.soaControl?.control?.titulo||'')}</p><p>SHA-256: <code>${App.esc(e.hashSha256)}</code></p>`;App.modal("evidenceValidationModal").show();}
async function saveEvidenceValidation(ev){ev.preventDefault();try{await App.api(`/evidencias/${document.getElementById("evidenceValidationId").value}/validar`,{method:"PUT",body:JSON.stringify({estado:document.getElementById("evidenceValidationState").value,observacion:document.getElementById("evidenceValidationNote").value})});App.modal("evidenceValidationModal").hide();App.toast("Decisión sobre evidencia registrada.");await refreshAuditor();}catch(e){App.toast(e.message,"error");}}
async function downloadAuditEvidence(id,name){try{const b=await App.api(`/evidencias/${id}/descargar`);App.downloadBlob(b,name||`evidencia_${id}`);}catch(e){App.toast(e.message,"error");}}
function renderFindings(){const q=document.getElementById("findingSearch").value.toLowerCase(),st=document.getElementById("findingStatus").value,sev=document.getElementById("findingSeverity").value;const data=auditorFindings.filter(h=>[h.titulo,h.descripcion,h.soaControl?.control?.codigo,h.riesgo?.codigo].some(v=>String(v||'').toLowerCase().includes(q))).filter(h=>!st||h.estado===st).filter(h=>!sev||h.severidad===sev);document.getElementById("findingMetrics").innerHTML=[auditMetric("Abiertos",auditorFindings.filter(h=>h.estado==='ABIERTO').length,"bi-search"),auditMetric("En tratamiento",auditorFindings.filter(h=>h.estado==='EN_TRATAMIENTO').length,"bi-tools"),auditMetric("Críticos",auditorFindings.filter(h=>h.severidad==='CRITICA'&&h.estado!=='CERRADO').length,"bi-radioactive"),auditMetric("Recurrentes",auditorFindings.filter(h=>h.recurrente&&h.estado!=='CERRADO').length,"bi-arrow-repeat")].join('');document.getElementById("findingsTable").innerHTML=data.map(h=>`<tr><td><strong>${App.esc(h.titulo)}</strong><br><small class="text-muted-app">${App.esc(h.descripcion)}</small></td><td>${App.esc(h.soaControl?.control?.codigo||'—')}<br><small class="text-muted-app">${App.esc(h.riesgo?.codigo||'Sin riesgo')}</small></td><td>${App.badge(h.severidad)}</td><td>${App.badge(h.estado)}</td><td>${h.recurrente?'<span class="badge-app b-high">Recurrente</span>':'No'}</td><td>${App.fmtDate(h.fechaDeteccion)}</td><td><button class="btn-app" onclick="openFindingModal(${h.id})"><i class="bi bi-pencil"></i></button>${h.estado!=='CERRADO'?` <button class="btn-app btn-success-app" onclick="closeFinding(${h.id})"><i class="bi bi-check2"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No hay hallazgos.</td></tr>';}
function openFindingModal(id,soaId){const h=auditorFindings.find(x=>x.id===id);document.getElementById("findingId").value=h?.id||'';document.getElementById("findingModalTitle").textContent=h?'Editar hallazgo':'Nuevo hallazgo';document.getElementById("findingTitle").value=h?.titulo||'';document.getElementById("findingDescription").value=h?.descripcion||'';document.getElementById("findingSeverityEdit").value=h?.severidad||'MEDIA';document.getElementById("findingStateEdit").value=h?.estado||'ABIERTO';document.getElementById("findingRecurrent").checked=!!h?.recurrente;document.getElementById("findingSoa").value=h?.soaControl?.id||soaId||'';document.getElementById("findingRisk").value=h?.riesgo?.id||'';App.modal("findingModal").show();}
async function saveFinding(e){e.preventDefault();const id=document.getElementById("findingId").value;const body={servicioId:auditorServiceId,soaControlId:document.getElementById("findingSoa").value?+document.getElementById("findingSoa").value:null,riesgoId:document.getElementById("findingRisk").value?+document.getElementById("findingRisk").value:null,titulo:document.getElementById("findingTitle").value,descripcion:document.getElementById("findingDescription").value,severidad:document.getElementById("findingSeverityEdit").value,estado:document.getElementById("findingStateEdit").value,recurrente:document.getElementById("findingRecurrent").checked};try{await App.api(`/hallazgos${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(body)});App.modal("findingModal").hide();App.toast("Hallazgo guardado.");await refreshAuditor();}catch(err){App.toast(err.message,"error");}}
async function closeFinding(id){const h=auditorFindings.find(x=>x.id===id);if(!h||!confirm("¿Cerrar este hallazgo?"))return;try{await App.api(`/hallazgos/${id}`,{method:"PUT",body:JSON.stringify({servicioId:auditorServiceId,soaControlId:h.soaControl?.id||null,riesgoId:h.riesgo?.id||null,titulo:h.titulo,descripcion:h.descripcion,severidad:h.severidad,estado:'CERRADO',recurrente:h.recurrente})});App.toast("Hallazgo cerrado.");await refreshAuditor();}catch(e){App.toast(e.message,"error");}}
function renderAuditRpm(){const q=document.getElementById("auditRpmSearch").value.toLowerCase(),p=document.getElementById("auditRpmPriority").value,all=latestAuditRpm(),data=all.filter(a=>[a.controlCodigo,a.controlTitulo,a.resumen,a.explicacion,...a.senales.map(s=>s.codigo),...a.decisiones.map(d=>d.accion)].some(v=>String(v||'').toLowerCase().includes(q))).filter(a=>!p||a.prioridad===p);document.getElementById("auditRpmMetrics").innerHTML=[auditMetric("Controles analizados",all.length,"bi-cpu"),auditMetric("Críticos",all.filter(a=>a.prioridad==='CRITICA').length,"bi-radioactive"),auditMetric("Altos",all.filter(a=>a.prioridad==='ALTA').length,"bi-exclamation-octagon"),auditMetric("Por validar",all.flatMap(a=>a.decisiones).filter(d=>d.estado==='PENDIENTE').length,"bi-person-check")].join('');document.getElementById("auditRpmList").innerHTML=data.length?data.map(a=>`<article class="card-app mb-3"><div class="d-flex justify-content-between gap-3"><div><h3>${App.esc(a.controlCodigo)} · ${App.esc(a.controlTitulo)}</h3><p class="small-app text-muted-app">${App.esc(a.resumen)}</p></div><div>${App.badge(a.prioridad)} <strong>${a.puntaje}/100</strong></div></div><div class="signal-list">${a.senales.map(s=>`<span class="signal" title="${App.esc(s.descripcion)}">${App.esc(s.codigo)} +${s.peso}</span>`).join('')}</div><p class="small-app">${App.esc(a.explicacion)}</p>${a.decisiones.map(d=>`<div class="priority-card"><div class="d-flex justify-content-between"><h4>${App.esc(App.pretty(d.tipoAccion))}</h4>${App.badge(d.estado)}</div><p>${App.esc(d.accion)}</p>${d.estado==='PENDIENTE'?`<button class="btn-app btn-success-app" onclick="auditDecision(${d.id},'APROBADA')">Aprobar</button> <button class="btn-app" onclick="auditDecision(${d.id},'MODIFICADA')">Modificar</button> <button class="btn-app btn-danger-app" onclick="auditDecision(${d.id},'RECHAZADA')">Rechazar</button>`:''}</div>`).join('')}</article>`).join(''):'<div class="card-app empty"><i class="bi bi-activity"></i>No hay análisis RPM.</div>';}
async function runRpmAudit(){try{const r=await App.api(`/rpm/analizar/servicio/${auditorServiceId}`,{method:'POST'});App.toast(`Análisis completado: ${r.analisisNuevos} nuevos, ${r.sinCambios} sin cambios.`);await refreshAuditor();goAuditSection('rpm');}catch(e){App.toast(e.message,'error');}}
async function auditDecision(id,state){let action=null,just='';if(state==='MODIFICADA'){action=prompt('Acción ajustada por el auditor:');if(!action)return;just=prompt('Fundamento del ajuste:')||'';}else{just=prompt(state==='RECHAZADA'?'Motivo del rechazo:':'Fundamento de la aprobación:')||'';if(state==='RECHAZADA'&&!just)return;}try{await App.api(`/rpm/decisiones/${id}`,{method:'PUT',body:JSON.stringify({estado:state,accion:action,justificacion:just})});App.toast('Validación RPM registrada.');await refreshAuditor();}catch(e){App.toast(e.message,'error');}}
function renderSignatures(){document.getElementById("signaturesList").innerHTML=auditorSignatures.length?auditorSignatures.map(f=>`<div class="priority-card"><div class="d-flex justify-content-between"><h4>${App.esc(f.nombreFirmante)} · ${App.esc(f.cargo)}</h4>${App.badge(f.estado)}</div><p>${App.fmtDate(f.fechaFirma)}</p></div>`).join(''):'<div class="empty"><i class="bi bi-pen"></i>No hay firmas registradas.</div>';}
function openSignatureModal(){document.getElementById("signatureForm").reset();document.getElementById("signatureName").value=auditorUser.nombre||'';document.getElementById("signatureRole").value='Auditor';App.modal("signatureModal").show();}
async function saveSignature(e){e.preventDefault();try{await App.api('/firmas',{method:'POST',body:JSON.stringify({nombreFirmante:document.getElementById('signatureName').value,cargo:document.getElementById('signatureRole').value,estado:document.getElementById('signatureState').value,servicioId:auditorServiceId})});App.modal('signatureModal').hide();App.toast('Firma registrada.');await refreshAuditor();}catch(err){App.toast(err.message,'error');}}
function renderAuditReport(){document.getElementById('auditReportSummary').innerHTML=`<div class="grid grid-3">${auditMetric('Avance SoA',`${auditorReport.porcentajeImplementacion}%`,'bi-list-check')}${auditMetric('Hallazgos',auditorFindings.length,'bi-search')}${auditMetric('Firmas',auditorSignatures.length,'bi-pen')}</div><div class="priority-card"><p>${auditorReport.evidenciasValidadas} evidencias validadas, ${auditorReport.evidenciasRechazadas} rechazadas y ${auditorReport.alertasRpm} alertas RPM altas/críticas.</p></div>`;}
async function downloadAuditReport(type){try{const b=await App.api(`/reportes/empresa/${auditorCompanyId}/${type}`);App.downloadBlob(b,`auditoria_global_iso_${auditorCompanyId}.${type==='pdf'?'pdf':'xlsx'}`);}catch(e){App.toast(e.message,'error');}}
function goAuditSection(s){document.querySelector(`[data-section="${s}"]`)?.click();}
function showAuditorFatal(m){document.querySelector('.main').innerHTML=`<div class="card-app empty"><i class="bi bi-exclamation-triangle"></i><h3>No fue posible cargar la auditoría</h3><p>${App.esc(m)}</p></div>`;}
