let currentUser, companyId, serviceId, serviceInfo, portal, profile, sectors=[], soa=[], risks=[], evidences=[], rpm=[], report;
const contextFlags=[
  ["manejaDatosSensibles","Maneja datos sensibles"],["usaServiciosNube","Usa servicios en la nube"],
  ["permiteTrabajoRemoto","Permite trabajo remoto"],["procesaPagos","Procesa pagos"],
  ["infraestructuraPropia","Cuenta con infraestructura propia"],["dependeProveedores","Depende de terceros/proveedores"],
  ["servicioCritico24x7","Opera servicios críticos 24/7"],["manejaMenores","Trata datos de menores"],
  ["operaOtIot","Opera entornos OT/IoT"]
];

document.addEventListener("DOMContentLoaded",async()=>{
  if(!App.requireAuth(["IMPLEMENTADOR"]))return;
  App.bindNavigation();bindTitles();bindForms();renderContextChecks();
  try{
    currentUser=await App.user();companyId=currentUser.empresa?.id;
    serviceInfo=await App.api("/servicios/mi-servicio");serviceId=serviceInfo.servicioId;companyId=serviceInfo.empresaId||companyId;
    document.getElementById("serviceLabel").textContent=`Servicio #${serviceId} · ${serviceInfo.sectorNombre||'Sin sector'} · ${App.pretty(serviceInfo.estado)}`;
    sectors=await App.api("/sectores");
    populateStaticSelects();
    await refreshImplementer();
  }catch(e){showFatal(e.message);}
});
function bindTitles(){document.querySelectorAll("[data-section]").forEach(b=>b.addEventListener("click",()=>document.getElementById("pageTitle").textContent=b.textContent.trim()));}
function bindForms(){
  document.getElementById("contextForm").addEventListener("submit",saveContext);
  document.getElementById("soaForm").addEventListener("submit",saveSoa);
  document.getElementById("riskForm").addEventListener("submit",saveRisk);
  document.getElementById("associationForm").addEventListener("submit",saveAssociation);
  document.getElementById("evidenceForm").addEventListener("submit",uploadEvidence);
  ["soaSearch","soaApplicability","soaState","soaRelevance"].forEach(id=>document.getElementById(id).addEventListener("input",renderSoa));
  ["riskSearch","riskCategory"].forEach(id=>document.getElementById(id).addEventListener("input",renderRisks));
  ["evidenceSearch","evidenceState"].forEach(id=>document.getElementById(id).addEventListener("input",renderEvidences));
  ["rpmSearch","rpmPriority"].forEach(id=>document.getElementById(id).addEventListener("input",renderRpm));
}
function renderContextChecks(){document.getElementById("contextChecks").innerHTML=contextFlags.map(([id,label])=>`<label class="form-check-app"><input id="ctx_${id}" type="checkbox"> ${label}</label>`).join("");}
function populateStaticSelects(){document.getElementById("ctxSector").innerHTML=sectors.map(s=>`<option value="${s.id}">${App.esc(s.nombre)}</option>`).join("");}
async function refreshImplementer(){
  try{
    [portal,profile,soa,risks,evidences,rpm,report]=await Promise.all([
      App.api(`/portal-empresa/empresa/${companyId}`),App.api(`/contexto/empresa/${companyId}`),App.api(`/soa/servicio/${serviceId}`),App.api(`/riesgos/servicio/${serviceId}`),App.api(`/evidencias/servicio/${serviceId}`),App.api(`/rpm/servicio/${serviceId}`),App.api(`/reportes/empresa/${companyId}`)
    ]);
    populateDynamicSelects();renderContext();renderDashboard();renderSoa();renderRisks();renderEvidences();renderRpm();renderReport();
  }catch(e){App.toast(e.message,"error");}
}
function metric(label,value,icon,hint=""){return `<div class="card-app metric"><i class="bi ${icon} icon"></i><div class="label">${App.esc(label)}</div><div class="value">${App.esc(value)}</div><div class="hint">${App.esc(hint)}</div></div>`;}
function renderDashboard(){
  document.getElementById("implementerMetrics").innerHTML=[
    metric("Avance general",`${portal.progresoGeneral}%`,"bi-speedometer2"),metric("Avance SoA",`${portal.soa.porcentaje}%`,"bi-list-check",`${portal.soa.aplicables} aplicables`),
    metric("Riesgos abiertos",portal.riesgos.abiertos,"bi-exclamation-diamond",`${portal.riesgos.criticos} críticos`),metric("Evidencias pendientes",portal.evidencias.pendientes,"bi-paperclip",`${portal.evidencias.validadas} validadas`),
    metric("Alertas RPM",portal.rpm.alertasActivas,"bi-activity",`${portal.rpm.pendientesValidacion} por validar`),metric("Hallazgos abiertos",portal.hallazgos.abiertos,"bi-search",`${portal.hallazgos.recurrentes} recurrentes`)
  ].join("");
  const stages=[["Contexto",portal.etapas.contexto],["Riesgos",portal.etapas.riesgos],["SoA",portal.etapas.soa],["Implementación",portal.etapas.implementacion],["Auditoría",portal.etapas.auditoria],["Cierre",portal.etapas.cierre]];
  document.getElementById("projectStages").innerHTML=stages.map(([n,v])=>`<div class="stage"><strong>${n}</strong><small>${v}%</small><div class="progress-app"><span style="width:${v}%"></span></div></div>`).join("");
  document.getElementById("prioritySummary").innerHTML=portal.prioridades.length?portal.prioridades.slice(0,6).map(x=>`<div class="priority-card ${String(x.prioridad).toLowerCase()}"><div class="d-flex justify-content-between"><h4>${App.esc(x.controlCodigo)} · ${App.esc(x.controlTitulo)}</h4>${App.badge(x.prioridad)}</div><p>${App.esc(x.resumen)}</p></div>`).join(""):'<div class="empty"><i class="bi bi-check-circle"></i>No hay alertas altas o críticas.</div>';
  document.getElementById("pendingActivities").innerHTML=portal.actividadesPendientes.length?portal.actividadesPendientes.map(a=>`<div class="priority-card ${String(a.prioridad).toLowerCase()}"><div class="d-flex justify-content-between"><h4>${App.esc(a.titulo)}</h4>${App.badge(a.prioridad)}</div><p>${App.esc(a.detalle)}</p></div>`).join(""):'<div class="empty"><i class="bi bi-check2-all"></i>No hay actividades pendientes registradas.</div>';
}
function renderContext(){
  document.getElementById("ctxSector").value=profile.sector?.id||serviceInfo.sectorId||sectors[0]?.id||"";document.getElementById("ctxSize").value=profile.tamano||"PEQUENA";document.getElementById("ctxOwner").value=profile.responsableSgsi||"";document.getElementById("ctxThreshold").value=profile.umbralAceptacion||6;document.getElementById("ctxScope").value=profile.alcanceSgsi||"";contextFlags.forEach(([id])=>document.getElementById(`ctx_${id}`).checked=!!profile[id]);
  const high=soa.filter(x=>x.nivelRelevancia==="ALTA").slice(0,7);document.getElementById("contextRecommendations").innerHTML=high.length?high.map(x=>`<div class="priority-card"><h4>${App.esc(x.control.codigo)} · ${App.esc(x.control.titulo)}</h4><p>${App.esc(x.recomendacionContextual)}</p></div>`).join(""):'<div class="empty">Aún no hay recomendaciones altas.</div>';
}
async function saveContext(e){e.preventDefault();const body={sectorId:+document.getElementById("ctxSector").value,tamano:document.getElementById("ctxSize").value,responsableSgsi:document.getElementById("ctxOwner").value,umbralAceptacion:+document.getElementById("ctxThreshold").value,alcanceSgsi:document.getElementById("ctxScope").value};contextFlags.forEach(([id])=>body[id]=document.getElementById(`ctx_${id}`).checked);try{await App.api(`/contexto/empresa/${companyId}`,{method:"PUT",body:JSON.stringify(body)});await App.api(`/soa/servicio/${serviceId}/inicializar`,{method:"POST"});App.toast("Contexto guardado y relevancia de controles recalculada.");await refreshImplementer();}catch(err){App.toast(err.message,"error");}}
function populateDynamicSelects(){
  document.getElementById("associationControl").innerHTML=soa.map(x=>`<option value="${x.control.id}">${App.esc(x.control.codigo)} · ${App.esc(x.control.titulo)}</option>`).join("");
  document.getElementById("evidenceSoa").innerHTML=soa.map(x=>`<option value="${x.id}">${App.esc(x.control.codigo)} · ${App.esc(x.control.titulo)}</option>`).join("");
}
function renderSoa(){const q=document.getElementById("soaSearch").value.toLowerCase(),a=document.getElementById("soaApplicability").value,s=document.getElementById("soaState").value,r=document.getElementById("soaRelevance").value;const data=soa.filter(x=>[x.control.codigo,x.control.titulo,x.responsable,x.observaciones].some(v=>String(v||'').toLowerCase().includes(q))).filter(x=>!a||x.aplicabilidad===a).filter(x=>!s||x.estadoImplementacion===s).filter(x=>!r||x.nivelRelevancia===r);document.getElementById("soaTable").innerHTML=data.map(x=>`<tr><td><strong>${App.esc(x.control.codigo)} · ${App.esc(x.control.titulo)}</strong><br><small class="text-muted-app">${App.esc(x.control.dominio)}</small></td><td>${App.badge(x.aplicabilidad)}<br><small class="text-muted-app">${App.esc(x.justificacionAplicabilidad||'Sin justificar')}</small></td><td>${App.badge(x.estadoImplementacion)}${App.progress(x.porcentajeImplementacion)}${x.vencido?'<span class="badge-app b-high">Fecha vencida</span>':''}</td><td>${App.badge(x.nivelRelevancia)}<br><small class="text-muted-app">${App.esc(x.recomendacionContextual)}</small></td><td>${x.evidencias.total}<br><small class="text-muted-app">${x.evidencias.validadas} validadas</small></td><td>${x.riesgos.length?x.riesgos.map(z=>`${App.esc(z.codigo)} ${App.badge(z.categoria||z.nivel)}`).join('<br>'):'—'}</td><td>${x.hallazgosAbiertos}</td><td class="nowrap"><button class="btn-app" onclick="openSoaModal(${x.id})"><i class="bi bi-pencil"></i></button> <button class="btn-app" onclick="openEvidenceModal(${x.id})"><i class="bi bi-paperclip"></i></button> <button class="btn-app" onclick="analyzeSoa(${x.id})"><i class="bi bi-activity"></i></button></td></tr>`).join("")||'<tr><td colspan="8" class="empty">No hay controles con esos filtros.</td></tr>';}
function openSoaModal(id){const x=soa.find(v=>v.id===id);if(!x)return;document.getElementById("soaId").value=id;document.getElementById("soaModalTitle").textContent=`${x.control.codigo} · ${x.control.titulo}`;document.getElementById("soaControlInfo").innerHTML=`<h4>${App.esc(x.control.pregunta)}</h4><p>${App.esc(x.control.descripcion)}</p><p><strong>Recomendación contextual:</strong> ${App.esc(x.recomendacionContextual)}</p>`;document.getElementById("soaEditApplicability").value=x.aplicabilidad;document.getElementById("soaEditState").value=x.estadoImplementacion;document.getElementById("soaEditProgress").value=x.porcentajeImplementacion;document.getElementById("soaEditOwner").value=x.responsable||"";document.getElementById("soaEditDate").value=x.fechaObjetivo||"";document.getElementById("soaEditJustification").value=x.justificacionAplicabilidad||"";document.getElementById("soaEditNotes").value=x.observaciones||"";App.modal("soaModal").show();}
async function saveSoa(e){e.preventDefault();const id=document.getElementById("soaId").value;const body={aplicabilidad:document.getElementById("soaEditApplicability").value,estadoImplementacion:document.getElementById("soaEditState").value,porcentajeImplementacion:+document.getElementById("soaEditProgress").value,responsable:document.getElementById("soaEditOwner").value,fechaObjetivo:document.getElementById("soaEditDate").value||null,justificacionAplicabilidad:document.getElementById("soaEditJustification").value,observaciones:document.getElementById("soaEditNotes").value};try{await App.api(`/soa/${id}`,{method:"PUT",body:JSON.stringify(body)});App.modal("soaModal").hide();App.toast("Control actualizado.");await refreshImplementer();}catch(err){App.toast(err.message,"error");}}
async function initializeSoa(){try{const x=await App.api(`/soa/servicio/${serviceId}/inicializar`,{method:"POST"});App.toast(`SoA actualizada: ${x.total} controles.`);await refreshImplementer();}catch(e){App.toast(e.message,"error");}}
function renderRisks(){const q=document.getElementById("riskSearch").value.toLowerCase(),c=document.getElementById("riskCategory").value;const data=risks.filter(x=>[x.codigo,x.nombre,x.activoInformacion,x.amenaza,x.responsable].some(v=>String(v||'').toLowerCase().includes(q))).filter(x=>!c||x.categoria===c);document.getElementById("riskMetrics").innerHTML=["CRITICO","ALTO","MEDIO","BAJO"].map(cat=>metric(App.pretty(cat),risks.filter(x=>x.categoria===cat).length,cat==='CRITICO'?'bi-radioactive':cat==='ALTO'?'bi-exclamation-octagon':cat==='MEDIO'?'bi-exclamation-triangle':'bi-check-circle')).join("");document.getElementById("risksTable").innerHTML=data.map(x=>`<tr><td><strong>${App.esc(x.codigo)} · ${App.esc(x.nombre)}</strong><br>${App.badge(x.estado)}</td><td>${App.esc(x.activoInformacion||'—')}<br><small class="text-muted-app">${App.esc(x.amenaza||'Sin amenaza registrada')}</small></td><td>${x.probabilidad}</td><td>${x.impacto}</td><td><strong>${x.nivelInherente}</strong> ${App.badge(x.categoria)}<br><small class="text-muted-app">Residual ${x.nivelResidual}</small></td><td>${App.esc(App.pretty(x.tratamiento))}<br><small class="text-muted-app">${App.esc(x.responsable||'Sin responsable')}</small></td><td>${x.controles.length?x.controles.map(z=>`<span class="signal">${App.esc(z.codigo)}</span>`).join(' '):'—'}</td><td class="nowrap"><button class="btn-app" onclick="openRiskModal(${x.id})"><i class="bi bi-pencil"></i></button> <button class="btn-app" onclick="openAssociationModal(${x.id})"><i class="bi bi-link-45deg"></i></button> <button class="btn-app btn-danger-app" onclick="deleteRisk(${x.id})"><i class="bi bi-trash"></i></button></td></tr>`).join("")||'<tr><td colspan="8" class="empty">No hay riesgos registrados.</td></tr>';}
function openRiskModal(id){const x=risks.find(v=>v.id===id);document.getElementById("riskId").value=x?.id||"";document.getElementById("riskModalTitle").textContent=x?'Editar riesgo':'Crear riesgo';const map={riskCode:'codigo',riskName:'nombre',riskAsset:'activoInformacion',riskOwner:'responsable',riskThreat:'amenaza',riskVulnerability:'vulnerabilidad',riskProbability:'probabilidad',riskImpact:'impacto',riskResidual:'nivelResidual',riskTreatment:'tratamiento',riskStatus:'estado',riskReviewDate:'fechaRevision',riskConsequence:'consecuencia',riskDescription:'descripcion'};Object.entries(map).forEach(([id,key])=>document.getElementById(id).value=x?.[key]??({riskProbability:1,riskImpact:1,riskResidual:1,riskTreatment:'MITIGAR',riskStatus:'ABIERTO'}[id]||''));App.modal("riskModal").show();}
async function saveRisk(e){e.preventDefault();const id=document.getElementById("riskId").value;const body={servicioId:serviceId,codigo:document.getElementById("riskCode").value,nombre:document.getElementById("riskName").value,activoInformacion:document.getElementById("riskAsset").value,amenaza:document.getElementById("riskThreat").value,vulnerabilidad:document.getElementById("riskVulnerability").value,consecuencia:document.getElementById("riskConsequence").value,probabilidad:+document.getElementById("riskProbability").value,impacto:+document.getElementById("riskImpact").value,nivelResidual:+document.getElementById("riskResidual").value,tratamiento:document.getElementById("riskTreatment").value,responsable:document.getElementById("riskOwner").value,estado:document.getElementById("riskStatus").value,fechaRevision:document.getElementById("riskReviewDate").value||null,descripcion:document.getElementById("riskDescription").value};try{await App.api(`/riesgos${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(body)});App.modal("riskModal").hide();App.toast("Riesgo guardado.");await refreshImplementer();}catch(err){App.toast(err.message,"error");}}
async function deleteRisk(id){if(!confirm("¿Eliminar el riesgo y sus relaciones con controles?"))return;try{await App.api(`/riesgos/${id}`,{method:"DELETE"});App.toast("Riesgo eliminado.");await refreshImplementer();}catch(e){App.toast(e.message,"error");}}
function openAssociationModal(id){document.getElementById("associationRiskId").value=id;document.getElementById("associationForm").reset();document.getElementById("associationRiskId").value=id;App.modal("associationModal").show();}
async function saveAssociation(e){e.preventDefault();const id=+document.getElementById("associationRiskId").value;const body={controlId:+document.getElementById("associationControl").value,tipoRelacion:document.getElementById("associationType").value,eficaciaEsperada:+document.getElementById("associationEffectiveness").value,observacion:document.getElementById("associationNote").value};try{await App.api(`/riesgos/${id}/controles`,{method:"POST",body:JSON.stringify(body)});App.modal("associationModal").hide();App.toast("Control asociado al riesgo.");await refreshImplementer();}catch(err){App.toast(err.message,"error");}}
function renderEvidences(){const q=document.getElementById("evidenceSearch").value.toLowerCase(),s=document.getElementById("evidenceState").value;const data=evidences.filter(x=>[x.nombreOriginal,x.descripcion,x.soaControl?.control?.codigo,x.soaControl?.control?.titulo].some(v=>String(v||'').toLowerCase().includes(q))).filter(x=>!s||x.estado===s);const today=new Date().toISOString().slice(0,10);document.getElementById("evidenceMetrics").innerHTML=[metric("Total",evidences.length,"bi-paperclip"),metric("Validadas",evidences.filter(x=>x.estado==='VALIDADA').length,"bi-patch-check"),metric("Pendientes",evidences.filter(x=>x.estado==='PENDIENTE').length,"bi-hourglass-split"),metric("Vencidas",evidences.filter(x=>x.fechaVencimiento&&x.fechaVencimiento<today).length,"bi-calendar-x")].join("");document.getElementById("evidenceTable").innerHTML=data.map(x=>`<tr><td><strong>${App.esc(x.nombreOriginal)}</strong><br><small class="text-muted-app">${App.esc(x.descripcion||'Sin descripción')}</small></td><td>${App.esc(x.soaControl?.control?.codigo||'—')}<br><small class="text-muted-app">${App.esc(x.soaControl?.control?.titulo||'')}</small></td><td>${App.badge(x.tipoEvidencia)}</td><td>${App.fmtDate(x.fechaCarga)}<br><small class="text-muted-app">Vence: ${App.fmtDate(x.fechaVencimiento)}</small></td><td>${App.badge(x.estado)}<br><small class="text-muted-app">${App.esc(x.observacionValidacion||'')}</small></td><td><code class="small-app">${App.esc((x.hashSha256||'').slice(0,14))}…</code></td><td class="nowrap"><button class="btn-app" onclick="downloadEvidence(${x.id},'${App.esc(x.nombreOriginal).replaceAll("'","&#39;")}')"><i class="bi bi-download"></i></button> <button class="btn-app btn-danger-app" onclick="deleteEvidence(${x.id})"><i class="bi bi-trash"></i></button></td></tr>`).join("")||'<tr><td colspan="7" class="empty">No hay evidencias.</td></tr>';}
function openEvidenceModal(soaId){document.getElementById("evidenceForm").reset();if(soaId)document.getElementById("evidenceSoa").value=soaId;App.modal("evidenceModal").show();}
async function uploadEvidence(e){e.preventDefault();const file=document.getElementById("evidenceFile").files[0];if(!file)return;const form=new FormData();form.append("archivo",file);form.append("descripcion",document.getElementById("evidenceDescription").value);form.append("tipo",document.getElementById("evidenceType").value);const exp=document.getElementById("evidenceExpiry").value;if(exp)form.append("fechaVencimiento",exp);try{await App.api(`/evidencias/soa/${document.getElementById("evidenceSoa").value}`,{method:"POST",body:form});App.modal("evidenceModal").hide();App.toast("Evidencia cargada y pendiente de validación.");await refreshImplementer();}catch(err){App.toast(err.message,"error");}}
async function downloadEvidence(id,name){try{const blob=await App.api(`/evidencias/${id}/descargar`);App.downloadBlob(blob,name||`evidencia_${id}`);}catch(e){App.toast(e.message,"error");}}
async function deleteEvidence(id){if(!confirm("¿Eliminar esta evidencia y su archivo físico?"))return;try{await App.api(`/evidencias/${id}`,{method:"DELETE"});App.toast("Evidencia eliminada.");await refreshImplementer();}catch(e){App.toast(e.message,"error");}}
function latestRpm(){const seen=new Set();return rpm.filter(x=>{const key=x.soaControlId||x.id;if(seen.has(key))return false;seen.add(key);return true;});}
function renderRpm(){const q=document.getElementById("rpmSearch").value.toLowerCase(),p=document.getElementById("rpmPriority").value;const all=latestRpm(),data=all.filter(x=>[x.controlCodigo,x.controlTitulo,x.resumen,x.explicacion,...x.senales.map(s=>s.codigo),...x.decisiones.map(d=>d.accion)].some(v=>String(v||'').toLowerCase().includes(q))).filter(x=>!p||x.prioridad===p);document.getElementById("rpmMetrics").innerHTML=[metric("Analizados",all.length,"bi-cpu"),metric("Críticos",all.filter(x=>x.prioridad==='CRITICA').length,"bi-radioactive"),metric("Altos",all.filter(x=>x.prioridad==='ALTA').length,"bi-exclamation-octagon"),metric("Pendientes",all.flatMap(x=>x.decisiones).filter(d=>d.estado==='PENDIENTE').length,"bi-person-check")].join("");document.getElementById("rpmList").innerHTML=data.length?data.map(a=>`<article class="card-app mb-3"><div class="d-flex justify-content-between gap-3"><div><h3>${App.esc(a.controlCodigo)} · ${App.esc(a.controlTitulo)}</h3><p class="small-app text-muted-app">${App.esc(a.resumen)}</p></div><div>${App.badge(a.prioridad)} <strong>${a.puntaje}/100</strong></div></div><div class="signal-list">${a.senales.map(s=>`<span class="signal" title="${App.esc(s.descripcion)}">${App.esc(s.categoria)} · ${App.esc(s.codigo)} +${s.peso}</span>`).join('')}</div><p class="small-app">${App.esc(a.explicacion)}</p>${a.memoriaSimilar?.length?`<div class="priority-card"><h4>Memoria similar disponible</h4><p>${a.memoriaSimilar.length} caso(s) previo(s) con resultado registrado.</p></div>`:''}<h3>Respuestas propuestas</h3>${a.decisiones.map(d=>`<div class="priority-card"><div class="d-flex justify-content-between"><h4>${App.esc(App.pretty(d.tipoAccion))}</h4>${App.badge(d.estado)}</div><p>${App.esc(d.accion)}</p>${d.justificacion?`<p><strong>Justificación:</strong> ${App.esc(d.justificacion)}</p>`:''}${d.estado==='PENDIENTE'?`<div class="mt-2"><button class="btn-app btn-success-app" onclick="validateDecision(${d.id},'APROBADA')">Aprobar</button> <button class="btn-app" onclick="validateDecision(${d.id},'MODIFICADA')">Modificar</button> <button class="btn-app btn-danger-app" onclick="validateDecision(${d.id},'RECHAZADA')">Rechazar</button></div>`:''}</div>`).join('')}<div class="mt-3"><button class="btn-app" onclick="registerMemory(${a.id},'${App.esc(a.prioridad)}')"><i class="bi bi-clock-history"></i> Registrar resultado en memoria</button></div></article>`).join(''):'<div class="card-app empty"><i class="bi bi-activity"></i>No hay análisis con estos filtros. Ejecute el motor RPM.</div>';}
async function runRpm(){const b=document.getElementById("runRpmButton");b.disabled=true;try{const x=await App.api(`/rpm/analizar/servicio/${serviceId}`,{method:"POST"});App.toast(`RPM completado: ${x.analisisNuevos} nuevos, ${x.sinCambios} sin cambios.`);await refreshImplementer();}catch(e){App.toast(e.message,"error");}finally{b.disabled=false;}}
async function analyzeSoa(id){try{await App.api(`/rpm/analizar/soa/${id}`,{method:"POST"});App.toast("Control analizado con RPM.");await refreshImplementer();goSection('rpm');}catch(e){App.toast(e.message,"error");}}
async function validateDecision(id,state){let action=null,just="";if(state==='MODIFICADA'){action=prompt("Escriba la acción modificada:");if(!action)return;just=prompt("Justifique el ajuste:")||"";}else if(state==='RECHAZADA'){just=prompt("Justifique el rechazo:")||"";if(!just)return;}else{just=prompt("Justificación o responsable de la aprobación (opcional):")||"";}try{await App.api(`/rpm/decisiones/${id}`,{method:"PUT",body:JSON.stringify({estado:state,justificacion:just,accion:action})});App.toast("Decisión RPM registrada.");await refreshImplementer();}catch(e){App.toast(e.message,"error");}}
async function registerMemory(id,priority){const result=prompt("Describa el resultado observado después de aplicar la respuesta:");if(!result)return;const effectiveness=Number(prompt("Efectividad estimada de 0 a 100:","70"));try{await App.api(`/rpm/${id}/memoria`,{method:"POST",body:JSON.stringify({prioridadFinal:priority,resultado:result,efectividadPorcentaje:Number.isFinite(effectiveness)?effectiveness:0})});App.toast("Caso almacenado como memoria RPM.");await refreshImplementer();}catch(e){App.toast(e.message,"error");}}
function renderReport(){document.getElementById("reportSummary").innerHTML=`<div class="grid grid-3">${metric("Controles",report.totalControles,"bi-journal-check")}${metric("Riesgos",report.totalRiesgos,"bi-exclamation-diamond")}${metric("RPM",report.alertasRpm,"bi-activity")}</div><div class="priority-card"><h4>${App.esc(report.empresaNombre||'Organización')}</h4><p>Avance SoA ${report.porcentajeImplementacion}% · ${report.evidenciasValidadas} evidencias validadas · ${report.totalCapacitaciones} capacitaciones.</p></div>`;}
async function loadReportSummary(){try{report=await App.api(`/reportes/empresa/${companyId}`);renderReport();App.toast("Resumen actualizado.");}catch(e){App.toast(e.message,"error");}}
async function downloadReport(type){try{const blob=await App.api(`/reportes/empresa/${companyId}/${type}`);App.downloadBlob(blob,`global_iso_${companyId}.${type==='pdf'?'pdf':'xlsx'}`);}catch(e){App.toast(e.message,"error");}}
function goSection(name){document.querySelector(`[data-section="${name}"]`)?.click();}
function showFatal(message){document.querySelector(".main").innerHTML=`<div class="card-app empty"><i class="bi bi-exclamation-triangle"></i><h3>No fue posible cargar el servicio</h3><p>${App.esc(message)}</p><button class="btn-app" data-logout>Cerrar sesión</button></div>`;document.querySelector('[data-logout]')?.addEventListener('click',App.logout);}
